/**
 * The build-time emitter.
 *
 * §14's math policy has one hard requirement: the simulation may not call
 * `Math.sin`. IEEE-754 exactly specifies `+ - * / %` and `Math.sqrt` and does NOT
 * specify the transcendentals, which legitimately differ across engines, versions
 * and platforms — so one `Math.sin` in the sim silently desynchronises every replay,
 * every leaderboard verification and every daily, and the failure looks like a
 * mysterious bug rather than a spec violation.
 *
 * The table is therefore computed HERE, once, at build time, and emitted as source
 * constants. Computing it at boot instead would reintroduce the platform's `Math.sin`
 * by a different door.
 *
 * §147.2: generated code is never committed, so the readable artifact is this file
 * and `src/gen/` is ignored. Every `npm run typecheck`, `build` and `test` re-emits
 * first, so a fresh clone cannot be missing it.
 */
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const GEN = join(ROOT, 'src', 'gen')

const BANNER = `// GENERATED by tools/emit.ts — do not edit, do not commit (§147.2).
// The source is the tool, not this file.
`

/**
 * §14's table. 4096 entries over [0, 2pi), sampled with linear interpolation, which
 * is multiply-and-add only.
 *
 * Why 4096 is the right size rather than a round number: the lerp error on a sine is
 * (step^2 / 8) * |sin''|, and step = 2pi/4096 = 1.534e-3, so the worst case is
 * 2.94e-7 — comfortably inside A-007's 1e-6 band, with the next size down (2048) at
 * 1.18e-6 and outside it. The size is derived, not chosen.
 */
export const SIN_TABLE_SIZE = 4096

export const emitSinTable = (): string => {
  const values: string[] = []
  for (let i = 0; i < SIN_TABLE_SIZE; i++) {
    // Shortest round-trip representation: JS guarantees Number(String(x)) === x, so
    // the emitted literal is the exact double, not an approximation of it.
    values.push(String(Math.sin((i * 2 * Math.PI) / SIN_TABLE_SIZE)))
  }
  // Fixed-width rows so a diff of the emitted file is legible when someone looks.
  const rows: string[] = []
  for (let i = 0; i < values.length; i += 8) rows.push('  ' + values.slice(i, i + 8).join(', ') + ',')
  return `${BANNER}
/** Entries over [0, 2pi). Power of two, so the wrap index is a mask rather than a modulo. */
export const SIN_TABLE_SIZE = ${SIN_TABLE_SIZE}

export const SIN_TABLE: readonly number[] = /* @__PURE__ */ Object.freeze([
${rows.join('\n')}
])
`
}

/**
 * §140.2's stroke face, packed.
 *
 * A node is `row * 7 + col` in 0..62, so six bits; a stroke is two nodes, so twelve.
 * That is where §140.2's "63 addressable points at 6 bits, a stroke as 12 bits" comes
 * from, and packing to it rather than to a convenient byte pair is what keeps §139.1's
 * "zero asset bytes" a measured claim rather than a rounded one.
 */
export const packFace = (glyphs: Readonly<Record<string, readonly string[]>>): string => {
  const chars = Object.keys(glyphs)
  const nodes: number[] = []
  const offsets: number[] = [0]

  for (const ch of chars) {
    for (const polyline of glyphs[ch] ?? []) {
      const points = polyline.split(' ').filter((t) => t.length > 0).map((token) => {
        const col = Number(token[0])
        const row = Number(token[1])
        if (!(col >= 0 && col < 7 && row >= 0 && row < 9)) {
          throw new Error(`glyph '${ch}': '${token}' is off the 7x9 grid`)
        }
        return row * 7 + col
      })
      // A single point is a dot — the tittle on an i, a full stop — and is stored as
      // a zero-length stroke rather than as a second concept.
      if (points.length === 1) {
        const only = points[0] ?? 0
        nodes.push(only, only)
        continue
      }
      for (let i = 0; i + 1 < points.length; i++) nodes.push(points[i] ?? 0, points[i + 1] ?? 0)
    }
    offsets.push(nodes.length / 2)
  }

  // Twelve bits per stroke, packed end to end.
  const bytes: number[] = []
  let acc = 0
  let bits = 0
  for (const node of nodes) {
    acc = (acc << 6) | (node & 63)
    bits += 6
    while (bits >= 8) {
      bits -= 8
      bytes.push((acc >> bits) & 255)
    }
  }
  if (bits > 0) bytes.push((acc << (8 - bits)) & 255)

  const base64 = Buffer.from(Uint8Array.from(bytes)).toString('base64')
  const strokes = nodes.length / 2

  return `${BANNER}
/** ${chars.length} glyphs, ${strokes} strokes, ${bytes.length} packed bytes (§140.2). */
export const FACE_GLYPHS = ${chars.length}
export const FACE_STROKE_COUNT = ${strokes}
export const FACE_BYTES = ${bytes.length}

export const FACE_CHARS = ${JSON.stringify(chars.join(''))}

/** Start stroke index per glyph, plus a terminator. */
export const FACE_OFFSETS: readonly number[] = Object.freeze(${JSON.stringify(offsets)})

/** Six bits per node, two nodes per stroke, base64 of the packed stream. */
export const FACE_PACKED = ${JSON.stringify(base64)}
`
}

/**
 * §142.6 — `core/loop` is GENERATED from `src/data/tickorder.ts`, so a system cannot
 * be added without choosing a step, and §14's golden hash certifies the order the
 * manifest STATES rather than the order the code drifted into.
 *
 * It lives under `src/gen/` rather than `src/core/` for one reason: `src/gen/` is the
 * directory §147.2's ignore rule covers, and a single generated file sitting inside a
 * hand-written directory is a generated file that eventually gets hand-edited.
 */
const SIM_ROOTS = ['core', 'grid', 'game', 'ui', 'growth'] as const

const DECLARES_STEP = /export const STEP = '([a-z]+)'/
/**
 * A `STEP` declaration is a claim to be WIRED, so the generator refuses one it cannot
 * honour. §142.1 counted twenty-two tick-ordered behaviours added since §26 and found
 * FOURTEEN with no step at all; the mirror of that failure is a step with no module —
 * a declaration that reads as scheduled and generates an import of a `step` nobody
 * wrote. The loop's PENDING list is where an unwired step belongs until it has one.
 */
const EXPORTS_STEP = /export const step\b|export function step\b/

interface Declared {
  readonly id: string
  /** Import specifier relative to src/gen/. */
  readonly from: string
}

const findSteps = (): Declared[] => {
  const found: Declared[] = []
  const walk = (dir: string, prefix: string): void => {
    let entries: string[]
    try {
      entries = readdirSync(dir)
    } catch {
      return // A system that does not exist yet declares no steps.
    }
    for (const entry of entries) {
      const path = join(dir, entry)
      if (statSync(path).isDirectory()) walk(path, `${prefix}/${entry}`)
      else if (entry.endsWith('.ts')) {
        const source = readFileSync(path, 'utf8')
        const match = DECLARES_STEP.exec(source)
        if (match?.[1] === undefined) continue
        if (!EXPORTS_STEP.test(source)) {
          throw new Error(`${prefix}/${entry} declares step '${match[1]}' and exports no step()`)
        }
        found.push({ id: match[1], from: `${prefix}/${entry}` })
      }
    }
  }
  for (const root of SIM_ROOTS) walk(join(ROOT, 'src', root), `../${root}`)
  return found
}

export const emitLoop = (order: readonly { index: number; id: string }[]): string => {
  const declared = findSteps()

  const seen = new Set<string>()
  for (const d of declared) {
    // Two modules claiming one step is an ordering the manifest does not express,
    // which is exactly the silent desync §26 warns about.
    if (seen.has(d.id)) throw new Error(`two modules declare step '${d.id}'`)
    seen.add(d.id)
    if (!order.some((s) => s.id === d.id)) {
      throw new Error(`${d.from} declares step '${d.id}', which src/data/tickorder.ts does not contain`)
    }
  }

  const wired = order
    .filter((s) => seen.has(s.id))
    .map((s) => {
      const d = declared.find((x) => x.id === s.id)
      if (d === undefined) throw new Error(`unreachable: ${s.id}`)
      return { index: s.index, id: s.id, from: d.from }
    })

  const imports = wired.map((s) => `import { step as ${s.id} } from '${s.from}'`).join('\n')
  const calls = wired.map((s) => `  ${s.id}(world) // step ${s.index}`).join('\n')
  const pending = order.filter((s) => !seen.has(s.id) && s.id !== 'timescale' && s.id !== 'tickend')

  return `${BANNER}
import type { World } from '../core/world.ts'
import { TICK_MS, MAX_CATCHUP_TICKS, PAUSE_GAP_MS } from '../core/tick.ts'
${imports}

/** The step ids this loop wires, in manifest order. */
export const WIRED: readonly string[] = ${JSON.stringify(wired.map((s) => s.id))}

/**
 * Steps the manifest declares and no module has claimed yet. Not a TODO list — it is
 * what stops a half-built loop from looking finished, and it is generated, so it
 * shrinks on its own as systems arrive.
 */
export const PENDING: readonly string[] = ${JSON.stringify(pending.map((s) => s.id))}

/** Step 24 (\`tickend\`): tick++, so a component added this frame cannot fire this frame. */
export const runTick = (world: World): void => {
${calls}
  world.tick++
}

/**
 * Re-exported from \`core/tick\`, which is a leaf (§145.4). The loop is the only
 * module allowed to cross systems, so it is the wrong place to DEFINE a constant
 * every simulation module needs — that would put each of them on an import of the
 * loop that imports them.
 */
export { TICK_MS, MAX_CATCHUP_TICKS, PAUSE_GAP_MS } from '../core/tick.ts'

export interface Clock {
  accumulator: number
  /**
   * §142.4 — the time-scale is a TICK GATE, so the target interval is
   * \`TICK_MS / scale\`. 1 is real time, 0.2 is §9's board, 0 is §99.3's paused, and
   * §149.3's harness runs it UPWARD at 50. Scaling \`dt\` instead would make §14's
   * golden hash a function of frame timing, which is the desync §26 exists to prevent.
   */
  scale: number
  /** Set when a gap exceeded PAUSE_GAP_MS. The caller decides what to show. */
  gapDetected: boolean
}

export const clock = (scale = 1): Clock => ({ accumulator: 0, scale, gapDetected: false })

/** Leave §9's auto-pause. The accumulator is already empty, so nothing catches up. */
export const resume = (c: Clock, world: World): void => {
  world.paused = false
  c.accumulator = 0
}

/**
 * Advance real time by \`dtMs\` and run whatever whole ticks that buys. Returns the
 * number of ticks run, which is 0 at scale 0 by construction rather than by a branch.
 */
export const advance = (c: Clock, world: World, dtMs: number): number => {
  c.gapDetected = false
  if (dtMs >= PAUSE_GAP_MS) {
    // §9: auto-pause on any gap over a second. The accumulator is discarded rather
    // than clamped, because catching up through a lid-close is a death the player
    // did not see.
    c.gapDetected = true
    c.accumulator = 0
    // The pause is SIMULATION state, not host state (\`core/lifecycle\`): a pause
    // driven from outside the world is an unrecorded input, and an unrecorded input
    // is a replay that does not reproduce.
    world.paused = true
    world.resumeGap = 1
    return 0
  }
  // §9 — the run ends when integrity does, and no revives in v0.1. \`world.over\` was
  // written by step 19 and read by NOTHING, so a dead run kept ticking: measured at
  // -1,160 integrity and 479 kills after the death it had already recorded, with the
  // host persisting that world to localStorage on the next visibility change. The
  // gate is the right home for it, beside \`paused\` and the scale, because all three
  // are the same question — is this world advancing — and §142.4 already answers it
  // in one place rather than in each of ten steps. It is checked on the CALL and
  // again in the catch-up loop, because a death can land mid-batch: at \`scale\` 50 a
  // single call runs many ticks, and a gate that only guards the call let a dead
  // world advance a further batch. A-011's x50-against-x1 symmetry check caught
  // exactly that, which is the whole reason it is asserted rather than assumed.
  if (world.paused || world.over || c.scale <= 0) return 0
  const interval = TICK_MS / c.scale
  c.accumulator += dtMs
  let ticks = 0
  while (c.accumulator >= interval && ticks < MAX_CATCHUP_TICKS && !world.over) {
    c.accumulator -= interval
    runTick(world)
    ticks++
  }
  // The clamp is a COUNT, not a ceiling on the accumulator. Clamping the float
  // instead measured four catch-up ticks where five were intended, because after
  // four subtractions the remainder sat 8e-15 below one interval. A budget of ticks
  // says what it means and cannot be eroded by the arithmetic it bounds.
  if (c.accumulator >= interval) c.accumulator = 0
  return ticks
}
`
}

const emit = (name: string, contents: string): void => {
  mkdirSync(GEN, { recursive: true })
  writeFileSync(join(GEN, name), contents)
  return void 0
}

if (import.meta.filename === process.argv[1]) {
  const { TICK_ORDER } = await import('../src/data/tickorder.ts')
  const { GLYPHS } = await import('../src/data/glyphstrokes.ts')
  emit('sintable.ts', emitSinTable())
  emit('loop.ts', emitLoop(TICK_ORDER))
  emit('strokefont.ts', packFace(GLYPHS))
  console.log('emitted src/gen/{sintable,loop,strokefont}.ts')
}
