/**
 * The build-time emitter.
 *
 * §14's math policy has one hard requirement: the simulation may not call
 * `Math.sin`. IEEE-754 exactly specifies `+ - * / %` and `Math.sqrt` and does NOT
 * specify the transcendentals, which legitimately differ across engines, versions
 * and platforms — so one `Math.sin` in the sim silently desynchronises every replay,
 * every leaderboard verification and every daily, and the failure looks like a
 * mysterious bug rather than a spec violation.
 *
 * The table is therefore computed HERE, once, at build time, and emitted as source
 * constants. Computing it at boot instead would reintroduce the platform's `Math.sin`
 * by a different door.
 *
 * §147.2: generated code is never committed, so the readable artifact is this file
 * and `src/gen/` is ignored. Every `npm run typecheck`, `build` and `test` re-emits
 * first, so a fresh clone cannot be missing it.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const GEN = join(ROOT, 'src', 'gen')

const BANNER = `// GENERATED by tools/emit.ts — do not edit, do not commit (§147.2).
// The source is the tool, not this file.
`

/**
 * §14's table. 4096 entries over [0, 2pi), sampled with linear interpolation, which
 * is multiply-and-add only.
 *
 * Why 4096 is the right size rather than a round number: the lerp error on a sine is
 * (step^2 / 8) * |sin''|, and step = 2pi/4096 = 1.534e-3, so the worst case is
 * 2.94e-7 — comfortably inside A-007's 1e-6 band, with the next size down (2048) at
 * 1.18e-6 and outside it. The size is derived, not chosen.
 */
export const SIN_TABLE_SIZE = 4096

export const emitSinTable = (): string => {
  const values: string[] = []
  for (let i = 0; i < SIN_TABLE_SIZE; i++) {
    // Shortest round-trip representation: JS guarantees Number(String(x)) === x, so
    // the emitted literal is the exact double, not an approximation of it.
    values.push(String(Math.sin((i * 2 * Math.PI) / SIN_TABLE_SIZE)))
  }
  // Fixed-width rows so a diff of the emitted file is legible when someone looks.
  const rows: string[] = []
  for (let i = 0; i < values.length; i += 8) rows.push('  ' + values.slice(i, i + 8).join(', ') + ',')
  return `${BANNER}
/** Entries over [0, 2pi). Power of two, so the wrap index is a mask rather than a modulo. */
export const SIN_TABLE_SIZE = ${SIN_TABLE_SIZE}

export const SIN_TABLE: readonly number[] = /* @__PURE__ */ Object.freeze([
${rows.join('\n')}
])
`
}

const emit = (name: string, contents: string): void => {
  mkdirSync(GEN, { recursive: true })
  writeFileSync(join(GEN, name), contents)
  return void 0
}

if (import.meta.filename === process.argv[1]) {
  emit('sintable.ts', emitSinTable())
  console.log(`emitted src/gen/sintable.ts (${SIN_TABLE_SIZE} entries)`)
}
